# Generated by Django 4.1.3 on 2022-12-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='passengers',
            new_name='passenger',
        ),
    ]
